name: Karl's Talks
title: Karl's Talks
subtitle: Slides for various programming talks by Karl Bielefeldt
email: karl.bielefeldt@gmail.com
description: >-
  Slides for various programming talks by Karl Bielefeldt
baseurl: "/talks"
url: "http://kbielefe.github.io"
twitter_username: softwarewhys
github_username:  kbielefe

theme: jekflix

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "talk"
      permalink: /:name

plugins:
  - jekyll-feed

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - vendor/

include:
  - node_modules
  - .nojekyll
