name: Publish Website

on:
  push:
    branches: [ master ]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.3
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.4
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install ruby dependencies
      run: bundle install
    - name: Install npm dependencies
      run: npm install
    - name: Build site
      run: bundle exec jekyll build --future
    - name: Publish to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.0.1
      with:
        build_dir: _site
      env:
        GITHUB_TOKEN: ${{ github.token }}
